### PR TITLE
Unmarshal Docker image labels separately

### LINKED ISSUE #2699: Created Timestamp issue with gcr.io repo not detected
**Describe the bug**
Flux will not detect Created timestamp for gcr.io repo.

Seeing this error in the logs:
```
ts=2019-12-17T03:05:02.232839857Z caller=repocachemanager.go:260 component=warmer canonical_name=gcr.io/my/registry auth={map[]} err="failed to parse 1 timestamp label(s) as RFC3339 (org.label-schema.build-date); ask the repository administrator to correct this as it conflicts with the spec" ref=gcr.io/my-registry:a6fb309227fe9f2354cf56eb72e10f60271ceab8
```

But if I run docker inspect on that image I get:
```
...
"Created": "2019-12-17T02:43:52.417086026Z"
...
```

If I run `list-images` the `CREATED` column is blank on those images and I see `15 images omitted`

Flux version: 1.16.0

I'm currently not using any labels in my docker containers (having trouble adding in build-date label via cloudbuild) I have two other kube installs running flux pulling from gcr.io with no issue (on older flux versions)

### PR DESCRIPTION
**Pull request by hiddeco**
To prevent the created field from never getting set when `LabelTimestampFormatError` is returned, which is used as a fallback in case the labels have an invalid (non RFC3339 date-time) format.

Fixes #2699

### CODE REVIEW

File: pkg/registry/client.go [hunk 1]
```diff
@@ -134,22 +134,28 @@ interpret:
 			Created time.Time `json:"created"`
 			OS      string    `json:"os"`
 			Arch    string    `json:"architecture"`
+		}
+		if err = json.Unmarshal([]byte(man.History[0].V1Compatibility), &v1); err != nil {
+			return ImageEntry{}, err
+		}
+
+		var config struct {
```
Comment (2opremio) [inline pkg/registry/client.go]: Please add a comment on why the config is unmarshaled separately. Also, it would be a good idea to add comment to each structure definition, linking to their authoritative source (e.g. OCI image standard )

Comment (hiddeco) [reply pkg/registry/client.go]: The authoritative sources of the image labels are already recorded in `image/image.go`. I have in-lined comments for the others.
