### PR TITLE
get ChangeSet from outside of paths if manifest generation is enabled

### LINKED ISSUE #3018: Flux overlooks commits that modifies Kustomize base manifests
**Describe the bug**

With Kustomize, Flux overlooks commits that modifies *base* manifests and does not report a sync event.

**To Reproduce**

1. Install Flux to a cluster by applying the manifest generated by `flux install`, with `--git-path=staging` and `--manifest-generation=true` options
1. Create a Git repository and place `.flux.yaml` and Kubernetes manifests like this: https://github.com/ordovicia/flux-bug/commit/ee00542138e6fc28f4dbfe592daedef45a00bfb3
1. Let Flux sync the cluster state with the repository
1. Modify `base/foo.yaml` like this: https://github.com/ordovicia/flux-bug/commit/3ba33d0ca5d4b94f829cf1e68a984df17ab9d9c6
1. Let Flux sync the cluster and repository again

**Expected behavior**

I expected that Flux reported a sync event that shows the new commit was applied to the cluster.
Specifically, I expected that `fluxd` emitted a log like this:

```
ts=2020-04-23T10:12:29.2014923Z caller=daemon.go:701 component=daemon event="Sync: aaa, <cluster>:namespace/foo" logupstream=false
```

**Broken behavior**

Flux did not report a sync event.

```
ts=2020-04-23T10:06:12.7421883Z caller=loop.go:141 component=sync-loop jobID=xxx state=in-progress
ts=2020-04-23T10:06:13.2277469Z caller=loop.go:153 component=sync-loop jobID=xxx state=done success=true
ts=2020-04-23T10:06:13.7285957Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/xxx/xxx branch=master HEAD=aaa
ts=2020-04-23T10:06:13.7628201Z caller=sync.go:73 component=daemon info="trying to sync git changes to the cluster" old=bbb new=aaa
ts=2020-04-23T10:06:14.0503525Z caller=sync.go:539 method=Sync cmd=apply args= count=1
ts=2020-04-23T10:06:14.2183084Z caller=sync.go:605 method=Sync cmd="kubectl apply -f -" took=167.7803ms err=null output="namespace/foo configured"
ts=2020-04-23T10:06:16.694326Z caller=loop.go:226 component=sync-loop state="tag flux" old=bbb new=aaa
ts=2020-04-23T10:06:17.2220011Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/xxx/xxx branch=master HEAD=aaa
```

**Possible causes**

I suspect that the root cause is that [`getChangeSet()`] only considers target paths (`d.GitConfig.Paths`; specified by `--git-path` option) and does not consider files outside of the paths.
`getChangeSet()` finds a series of commits, from a given range of commits, that changed files under the target paths.
If the range of commits only changed files outside of the target paths, `getChangeSet()` returns an empty list of commits.

Then, [`logCommitEvent()`] attempts to report a sync event, but `getChangeSet()` found that there were no new commits Flux needed to apply (i.e. `len(c.commits) == 0`), and `logCommitEvent()` does not report any event.

[`getChangeSet()`]: https://github.com/fluxcd/flux/blob/bf5f494fd88392fa778527604c8c4e24375c5504/pkg/daemon/sync.go#L68
[`logCommitEvent()`]: https://github.com/fluxcd/flux/blob/bf5f494fd88392fa778527604c8c4e24375c5504/pkg/daemon/sync.go#L372

**Additional context**

- Flux version: `docker.io/fluxcd/flux:1.19.0`
- Kubernetes version: v1.17.0 (I was used Kind)
- Git provider: GitHub
- Container registry provider: N/A

### PR DESCRIPTION
**Pull request by ordovicia**
`getChangeSet()` in `pkg/daemon/sync.go` now does not consider target paths
while identifying what series of commits changed files Flux is watching
when the manifest generation is enabled.

With manifest generation enabled, Kubernetes resources can be modified
by changes in files outside of target paths.
`getChangeSet()` now conservatively identifies commits that may have
changed resources when the manifest generation is enabled.

Fixes #3018

### CODE REVIEW

**Comment by ordovicia** [comment]
@hiddeco @stefanprodan Could you please take a look at this and #3039? Thank you.

File: pkg/daemon/sync_test.go [hunk 1]
```diff
@@ -406,8 +406,126 @@ func TestDoSync_WithNewCommit(t *testing.T) {
...
+	}
+
+	// It applies everything
+	if syncCalled != 1 {
+		t.Errorf("Sync was not called once, was called %d times", syncCalled)
+	} else if syncDef == nil {
+		t.Errorf("Sync was called with a nil syncDef")
+	}
+
+	// The emitted event has no workload ids
```
Comment (squaremo) [inline pkg/daemon/sync_test.go:496]: This comment seems to be misleading -- what is tested below is that there's an event _with_ a workload ID

Comment (ordovicia) [reply pkg/daemon/sync_test.go]: Fixed. Thank you!

**Comment by ordovicia** [comment]
> Is it superseded by #3039?

No, this PR and #3039 are independent and they address different issues.

**Comment by ordovicia** [comment]
@squaremo This PR is ready for merge. Is there anything I am supposed to do?
